easy_admin:
    site_name: 'Cubyke'
    design:
        brand_color: '#e23342'
        form_theme:
            - '@EasyAdmin/Form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    entities:
        # List the entity class name you want to manage
        Tour:
            class: App\Entity\Tour
            label: Tour
            form:
                title: 'Add or update a Tour'
                fields:
                    - {property: titleEn, label: 'Title in English'}
                    - {property: titleEs, label: 'Title in Spanish'}
                    - {property: titleDe, label: 'Title in German'}
                    - {property: descriptionEn, label: 'Description in English'}
                    - {property: descriptionEs, label: 'Description in Spanish'}
                    - {property: descriptionDe, label: 'Description in German'}
                    - {property: urlEn, label: 'Url in trekksoft in English'}
                    - {property: urlEs, label: 'Url in trekksoft in Spanish'}
                    - {property: urlDe, label: 'Url in trekksoft in German'}
                    - {property: file, type: file, label: Image}
                    - {property: position, label: Position}
            list:
                title: 'Tours'
                fields:
                    - {property: titleEn, label: Title (EN)}
                    - {property: descriptionEn, label: Description (EN)}
                    - {property: urlEn, label: Url (EN)}
                    - {property: position, label: Position}
                    - {property: getWebPath, type: image, label: Image}

        BlogEntry:
            class: App\Entity\BlogEntry
            label: Blog Entry
            form:
                title: 'Add or update a post'
                fields:
                    - {property: titleEn, label: 'Title in English'}
                    - {property: titleEs, label: 'Title in Spanish'}
                    - {property: titleDe, label: 'Title in German'}
                    - {property: file, type: 'file', label: 'Image at Hero'}
                    - {property: imagesGallery, label: 'Images galleries'}
                    - {property: textAtBeginningEn, type: fos_ckeditor, label: 'Beginning of the Post in english'}
                    - {property: textAtEndingEn, type: fos_ckeditor, label: 'End of the Post in english'}
                    - {property: textAtBeginningEs, type: fos_ckeditor, label: 'Beginning of the Post in spanish'}
                    - {property: textAtEndingEs, type: fos_ckeditor, label: 'End of the Post in spanish'}
                    - {property: textAtBeginningDe, type: fos_ckeditor, label: 'Beginning of the Post in german'}
                    - {property: textAtEndingDe, type: fos_ckeditor, label: 'End of the Post in german'}
                    - {property: datetime, type: datetime, label: 'Date'}
            list:
                title: 'Blog entries'
                fields:
                    - {property: titleEn, label: Title}
                    - {property: datetime, label: DateTime}
                    - {property: getWebPath, type: image, label: Image}
                    - {property: textAtBeginningEn, label: 'Content (EN)'}

        TeamMember:
            class: App\Entity\TeamMember
            label: Team member
            form:
                title: 'Add team member'
                fields:
                    - {property: name, label: 'Name'}
                    - {property: position, label: 'Position in Company'}
                    - {property: file, type: 'file', label: 'Image'}
                    - {property: descriptionEn, type: fos_ckeditor, label: 'Description in english'}
                    - {property: descriptionEs, type: fos_ckeditor, label: 'Description in spanish'}
                    - {property: descriptionDe, type: fos_ckeditor, label: 'Description in german'}
                    - {property: orderPos, label: 'Position for order'}
            list:
                title: 'Team members'
                fields:
                    - {property: 'name', label: 'Name'}
                    - {property: 'position'}
                    - {property: 'descriptionEn', label: 'Description (EN)'}
                    - {property: 'getWebPath', label: 'Image', type: 'image'}
                    - {property: 'orderPos', label: 'Order'}

        Bike:
            class: App\Entity\Bike
            label: Bike
            form:
                title: 'Add bike'
                fields:
                    - {property: name, label: 'Name'}
                    - {property: file, type: 'file', label: 'Image'}
            list:
                title: 'Bikes'
                fields:
                    - {property: 'name', label: 'Name'}
                    - {property: 'getWebPath', label: 'Image', type: 'image'}

        BasicPage:
            class: App\Entity\BasicPage
            label: Basic Page
            form:
                title: 'Add Basic Page'
                fields:
                    - {property: codeName, label: 'Code Name'}
                    - {property: titleEn, label: 'Title in English'}
                    - {property: titleEs, label: 'Title in Spanish'}
                    - {property: titleDe, label: 'Title in Deutsch'}
                    - {property: contentEn, type: fos_ckeditor, label: 'Content in English'}
                    - {property: contentEs, type: fos_ckeditor, label: 'Content in Spanish'}
                    - {property: contentDe, type: fos_ckeditor, label: 'Content in Deutsch'}
                    - {property: file, type: file, label: 'Image at Hero'}
            list:
                title: 'Basic Pages'
                fields:
                    - {property: 'codename', label: 'Code Name'}
                    - {property: 'titleEn', label: 'Title (EN)'}
                    - {property: 'contentEn', label: 'Content (EN)'}
                    - {property: 'getWebPath', type: image, label: 'Image'}

        ImageFile:
            class: App\Entity\ImageFile
            label: Images
            form:
                title: 'Add or update an image'
                fields:
                    - {property: 'name', label: Name}
                    - {property: 'category', label: Category, help: 'Use for categorized content Ex: blog'}
                    - {property: 'file', type: file, label: 'Imagen'}
                    - {property: 'description', label: Description}
            list:
                title: 'Images'
                fields:
                    - {property: 'name', label: Name}
                    - {property: 'category', label: Category}
                    - {property: 'getWebPath', label: Image, type: 'image'}
                    - {property: 'description', label: Description}

        KeyValues:
            class: App\Entity\KeyValues
            label: Key Values
            form:
                title: 'Add Key'
                fields:
                    - {property: name, label: 'Key'}
                    - {property: value, label: 'Value'}
            list:
                title: Key Values
                fields:
                    - {property: name, label: 'Key'}
                    - {property: value, label: 'Value'}
